title: Kor-SVS
description: For Korean SVS development
theme: just-the-docs

url: https://kor-svs.github.io/docs/

color_scheme: dark

aux_links:
    Template Repository: https://github.com/just-the-docs/just-the-docs-template
