title: Kor-SVS 문서
description: 한국어 음성합성에 대한 참고문서
theme: just-the-docs

url: https://kor-svs.github.io/docs/

color_scheme: dark

aux_links:
    Template Repository: https://github.com/just-the-docs/just-the-docs-template
