title: Coda 문서
description: Coda팀에서 제공하는 음성합성에 대한 참고문서
theme: just-the-docs

url: https://coda-svs.github.io/docs/

color_scheme: dark

aux_links:
    Template Repository: https://github.com/Coda-SVS/docs
